spring.application.name=bookstore

spring.datasource.url=jdbc:postgresql://localhost:5433/bookstore
spring.datasource.username=bookstore
spring.datasource.password=bookstore

spring.jpa.hibernate.ddl-auto=update
